//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class BIENBANSUCO
    {
        public string MaBienBan
        {
            get;
            set;
        }

        public string LoaiSuCo
        {
            get;
            set;
        }

        public string NguoiChiuTrachNhiem
        {
            get;
            set;
        }

        public string NguyenNhan
        {
            get;
            set;
        }

        public string ThoiGian
        {
            get;
            set;
        }

        public string HuongGiaiQuyet
        {
            get;
            set;
        }

        public string MaNV
        {
            get;
            set;
        }

        public int Id
        {
            get;
            set;
        }

        public THIETHAI THIETHAI
        {
            get;
            set;
        }

    }

}