//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace QuanLyNhaHang.Models
{
    public class BOPHAN 
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        
        public int TruongBPId
        {
            get;
            set;
        }
        public string MaBP
        {
            get;
            set;
        }

        public string TenBP
        {
            get;
            set;
        }

        //public string TruongBP
        //{
        //    get;
        //    set;
        //}

        //public virtual NHANVIEN NHANVIEN
        //{
        //    get;
        //    set;
        //}

    }

}