//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class CHEBIEN
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id
    {
        get;
        set;
    }

    public string MaMon
	{
		get;
		set;
	}

	public string MaNL
	{
		get;
		set;
	}

	public string LuongDung
	{
		get;
		set;
	}


	//public virtual NGUYENLIEU getNguyenLieu()
	//{
	//	throw new System.NotImplementedException();
	//}

	//public virtual MONAN getMonAn()
	//{
	//	throw new System.NotImplementedException();
	//}

}

