//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class DATBAN
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id
    {
        get;
        set;
    }
    public string Ngay
	{
		get;
		set;
	}



	public string SoNguoi
	{
		get;
		set;
	}

	public string Gio
	{
		get;
		set;
	}

	public string SoDT
	{
		get;
		set;
	}

	public string HoTen
	{
		get;
		set;
	}

}

