//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class DATBAN: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name ="Ngày đặt")]
        [Required(ErrorMessage = "Vui lòng nhập ngày đặt bàn")]
        public string Ngay
        {
            get;
            set;
        }

        [Display(Name ="Số Người")]
        [Required(ErrorMessage = "Vui lòng nhập số người")]
        [Range(0,500,ErrorMessage ="Số người chưa hợp lệ")]
        public string SoNguoi
        {
            get;
            set;
        }

        [Display(Name ="Giờ đặt")]
        [Required(ErrorMessage ="Vui lòng nhập giờ đặt bàn")]
        public string Gio
        {
            get;
            set;
        }

        [Display(Name ="Số điện thoại")]
        [Required(ErrorMessage ="Vui lòng nhập số điện thoại")]
        [Phone(ErrorMessage ="Số điện thoại chưa hợp lệ")]
        [StringLength(15, ErrorMessage = "Số điện thoại chưa hợp lệ", MinimumLength = 6)]
        public string SoDT
        {
            get;
            set;
        }

        [Display(Name ="Họ tên")]
        [Required(ErrorMessage ="Vui lòng nhập họ tên")]
        [MaxLength(50, ErrorMessage ="Họ tên không quá 50 kí tự")]
        public string HoTen
        {
            get;
            set;
        }

    }

}

