//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class DATBAN: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }
        [Required]
        public string Ngay
        {
            get;
            set;
        }

        [Required]
        public string SoNguoi
        {
            get;
            set;
        }

        public string Gio
        {
            get;
            set;
        }

        [Required]
        public string SoDT
        {
            get;
            set;
        }

        [Required]
        public string HoTen
        {
            get;
            set;
        }

    }

}

