//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class HOADONNHAPHANG: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã hóa đơn")]
        [Required(ErrorMessage = "Vui lòng nhập mã hóa đơn")]
        [MaxLength(12, ErrorMessage = "Mã hóa đơn không quá 12 kí tự")]
        public string MaHD
        {
            get;
            set;
        }

        [Display(Name = "Mã món ăn")]
        [Required(ErrorMessage = "Vui lòng chọn mã yêu cầu")]
        public string MaYeuCau
		{
            get;
            set;
        }

        //kết bảng
        //public YEUCAUNHAPHANG fYEUCAUNHAPHANG
        //{
        //	get;
        //	set;
        //}

        [Display(Name = "Thời gian nhập")]
        [Required(ErrorMessage = "Vui lòng nhập thời gian nhập")]
        public string ThoiGianNhap
        {
            get;
            set;
        }

        [Display(Name = "Thời gian nhập")]
        [Required(ErrorMessage = "Vui lòng nhập thời gian nhập")]
        public string MaNV
        {
            get;
            set;
        }

        //kết bảng
        //public NHANVIEN fNHANVIEN
        //{
        //	get;
        //	set;
        //}

        [Display(Name = "Mã nhà cung cấp")]
        [Required(ErrorMessage = "Vui lòng chọn mã nhà cung cấp")]
        public string MaNCC
        {
            get;
            set;
        }

        //kết bảng
        //public NHACUNGCAP fNHACUNGCAP
        //{
        //	get;
        //	set;
        //}
        [Display(Name = "Thành tiền")]
        [DataType(DataType.Currency)]
        public string ThanhTien
        {
            get;
            set;
        }



        //public virtual PHIEUCHI PHIEUCHI
        //{
        //	get;
        //	set;
        //}

        //public virtual YEUCAUNHAPHANG NHAPHANG
        //{
        //	get;
        //	set;
        //}

        //public virtual PHIEUCHI getPhieuChi()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual YEUCAUNHAPHANG getYeuCauNhapHang()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

