//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class HOADONNHAPHANG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        public int NhanVienId
        {
            get;
            set;
        }

        public int NhaCungCapId
        {
            get;
            set;
        }
        public string SoHD
        {
            get;
            set;
        }

        public string ThoiGianNhap
        {
            get;
            set;
        }

        public string ThanhTien
        {
            get;
            set;
        }

        public string NgayLap
        {
            get;
            set;
        }

        //public virtual NHANVIEN NHANVIEN
        //{
        //    get;
        //    set;
        //}

        //public virtual NHACUNGCAP NHACUNGCAP
        //{
        //    get;
        //    set;
        //}

        //public virtual ICollection<NHAPHANG> NHAPHANG
        //{
        //    get;
        //    set;
        //}
    }

}