//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class LOAISUCO: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name ="Mã loại sự cố")]
        [Required(ErrorMessage ="Vui lòng nhập mã sự cố")]
        [MaxLength(12, ErrorMessage ="Mã sự cố không quá 12 kí tự")]
        public string MaLoaiSuCo
        {
            get;
            set;
        }

        [Display(Name ="Tên loại sự cố")]
        [Required(ErrorMessage ="Vui lòng nhập tên loại sự cố")]
        [MaxLength(50, ErrorMessage ="Tên loại sự cố không quá 50 kí tự")]
        public string TenLoaiSuCo
        {
            get;
            set;
        }

        [Display(Name = "Mã bộ phận xử lý")]
        [Required(ErrorMessage = "Vui lòng nhập mã bộ phận xử lý")]
        [MaxLength(12, ErrorMessage = "Mã bộ phận xử lý không quá 12 kí tự")]
        public string MaBoPhanXuLy
        {
            get;
            set;
        }
		
		//kết bảng
		public virtual BOPHAN fBOPHAN
		{
			get;
			set;
		}
    }
}


