//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class LOAISUCO
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        public string MaLoaiSuCo
        {
            get;
            set;
        }

        public string TenLoaiSuCo
        {
            get;
            set;
        }

        public int MaBoPhanXuLy
        {
            get;
            set;
        }

        //public virtual BIENBANSUCO BIENBANSUCO
        //{
        //	get;
        //	set;
        //}

        //public virtual List<BIENBANSUCO> getListBienBanSuCo()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual BOPHAN getBoPhan()
        //{
        //	throw new System.NotImplementedException();
        //}

    }
}


