//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class LUOTKHACH
    {
        public string MaLuot
        {
            get;
            set;
        }

        public int SoBan
        {
            get;
            set;
        }

        public string ThoiGianRa
        {
            get;
            set;
        }

        public string ThoiGianVao
        {
            get;
            set;
        }

        public int Id
        {
            get;
            set;
        }

        public YEUCAUMONAN YEUCAUMONAN
        {
            get;
            set;
        }

        public PHIEUTHU PHIEUTHU
        {
            get;
            set;
        }

    }

}