//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class MONAN: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã món ăn")]
        [Required(ErrorMessage = "Vui lòng nhập mã món ăn")]
        [MaxLength(12, ErrorMessage = "Mã món ăn không quá 12 kí tự")]
        public string MaMon
        {
            get;
            set;
        }

        [Display(Name = "Tên món ăn")]
        [Required(ErrorMessage = "Vui lòng nhập tên món ăn")]
        [MaxLength(50, ErrorMessage = "Tên món ăn không quá 50 kí tự")]
        public string TenMon
        {
            get;
            set;
        }

        [Display(Name = "Giá")]
        [Required(ErrorMessage = "Vui lòng giá của món ăn")]
        [Range(0,int.MaxValue,ErrorMessage ="Giá món ăn không hợp lệ")]
        public string Gia
        {
            get;
            set;
        }

        [Display(Name = "Mã loại món")]
        [Required(ErrorMessage = "Vui lòng nhập mã loại món")]
        [MaxLength(12, ErrorMessage = "Mã loại món không được quá 12 kí tự")]
        public string MaLoaiMon
        {
            get;
            set;
        }
		
		//kết bảng
		public virtual LOAIMONAN fLOAIMONAN
		{
			get;
			set;
		}
    }

}

