//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class MONAN: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã món")]
        [Required(ErrorMessage = "Vui lòng nhập mã món")]
        [MaxLength(12, ErrorMessage = "Mã món không quá 12 kí tự")]
        public string MaMon
        {
            get;
            set;
        }

        [Display(Name = "Tên món")]
        [Required(ErrorMessage = "Vui lòng nhập tên món")]
        [MaxLength(50, ErrorMessage = "Tên món không quá 12 kí tự")]
        public string TenMon
        {
            get;
            set;
        }

        [Display(Name = "Giá")]
        [Required(ErrorMessage = "Vui lòng nhập giá")]
        [DataType(DataType.Currency)]
        public string Gia
        {
            get;
            set;
        }

        [Display(Name = "Tên loại món")]
        [Required(ErrorMessage = "Vui lòng chọn mã loại món")]
        public string MaLoaiMon
        {
            get;
            set;
        }
		
		//kết bảng
		//public virtual LOAIMONAN fLOAIMONAN
		//{
		//	get;
		//	set;
		//}
        //public virtual YEUCAUMONAN YEUCAUMONAN
        //{
        //	get;
        //	set;
        //}

        //public virtual CHEBIEN CHEBIEN
        //{
        //	get;
        //	set;
        //}

        //public virtual List<NGUYENLIEU> getListNguyenLieu()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual List<YEUCAUMONAN> getListYeuCauMonAn()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

