//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class NGUYENLIEU: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã nguyên liệu")]
        [Required(ErrorMessage = "Vui lòng nhập mã nguyên liệu")]
        [MaxLength(12, ErrorMessage = "Mã nguyên liệu không được quá 12 kí tự")]
        public string MaNL
        {
            get;
            set;
        }

        [Display(Name = "Tên nguyên liệu")]
        [Required(ErrorMessage = "Vui lòng nhập tên nguyên liệu")]
        [MaxLength(50, ErrorMessage = "Tên nguyên liệu không được quá 50 kí tự")]
        public string TenNL
        {
            get;
            set;
        }

        [Display(Name = "Đơn vị tính")]
        [Required(ErrorMessage = "Vui lòng nhập đơn vị tính")]
        [MaxLength(20, ErrorMessage = "Đơn vị tính không được quá 20 kí tự")]
        public string DVT
        {
            get;
            set;
        }

        [Display(Name = "Giá")]
        [Required(ErrorMessage = "Vui lòng giá nguyên liệu")]
        [Range(0, int.MaxValue, ErrorMessage = "Giá nguyên liệu không hợp lệ")]
        public string Gia
        {
            get;
            set;
        }

        [Display(Name = "Xuất xứ")]
        public string XuatXu
        {
        	get;
        	set;
        }
    }

}

