//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class NGUYENLIEU
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        public string DVT
        {
            get;
            set;
        }

        public string Gia
        {
            get;
            set;
        }

        public string MaNL
        {
            get;
            set;
        }

        public string TenNL
        {
            get;
            set;
        }

        public string XuatXu
        {
            get;
            set;
        }

        //public virtual CHEBIEN CHEBIEN
        //{
        //    get;
        //    set;
        //}

        //public virtual NGUYENLIEUTRONGKHO KHO
        //{
        //    get;
        //    set;
        //}

    }

}