//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class NGUYENLIEU
    {
        public int Id
        {
            get;
            set;
        }

        public string DVT
        {
            get;
            set;
        }

        public string Gia
        {
            get;
            set;
        }

        public string MaNL
        {
            get;
            set;
        }

        public string TenNL
        {
            get;
            set;
        }

        public string XuatXu
        {
            get;
            set;
        }

        public virtual CHEBIEN CHEBIEN
        {
            get;
            set;
        }

        public virtual NGUYENLIEUTRONGKHO KHO
        {
            get;
            set;
        }

    }

}