//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class NGUYENLIEUTRONGKHO: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã nguyên liệu")]
        [Required(ErrorMessage = "Vui lòng chọn mã nguyên liệu")]
        public string MaNL
        {
            get;
            set;
        }

        //kết bảng
        //public virtual NGUYENLIEU fNGUYENLIEU
        //{
        //	get;
        //	set;
        //}

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public float SoLuong
        {
            get;
            set;
        }

        [Display(Name = "Tình trạng")]
        [Required(ErrorMessage = "Vui lòng nhập tình trạng")]
        public string TinhTrang
        {
            get;
            set;
        }

        //public virtual NGUYENLIEU getNguyenLieu()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

