//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class NGUYENLIEUTRONGKHO: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Required]
        public string MaNL
        {
            get;
            set;
        }
		
		//kết bảng
		//public virtual NGUYENLIEU fNGUYENLIEU
		//{
		//	get;
		//	set;
		//}

        [Required]
        public int SoLuong
        {
            get;
            set;
        }

        [Required]
        public bool TinhTrang
        {
            get;
            set;
        }

        //public virtual NGUYENLIEU getNguyenLieu()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

