//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class NHACUNGCAP
    {
        public int Id
        {
            get;
            set;
        }

        public string MaNCC
        {
            get;
            set;
        }

        public string TenNCC
        {
            get;
            set;
        }

        public string DiaChi
        {
            get;
            set;
        }

        public string SoDT
        {
            get;
            set;
        }

        public string SoNo
        {
            get;
            set;
        }

        public virtual NHAPHANG NHAPHANG
        {
            get;
            set;
        }

    }

}