//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace QuanLyNhaHang.Models
{
    public class NHANVIEN
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        //public int HoaDonNhapHangId
        //{
        //    get;
        //    set;
        //}

        //public int BienBanSuCoId
        //{
        //    get;
        //    set;
        //}

        //public int PhieuChiId
        //{
        //    get;
        //    set;
        //}

        //public int PhieuThuId
        //{
        //    get;
        //    set;
        //}

        public int BoPhanId
        {
            get;
            set;
        }

        public string MaNV
        {
            get;
            set;
        }

        public string TenNV
        {
            get;
            set;
        }

        public int SoDT
        {
            get;
            set;
        }

        public string DiaChi
        {
            get;
            set;
        }

        public string CMND
        {
            get;
            set;
        }

        //public virtual BOPHAN BOPHAN
        //{
        //    get;
        //    set;
        //}
        //public virtual HOADONNHAPHANG HOADONNHAPHANG
        //{
        //    get;
        //    set;
        //}

        //public virtual BIENBANSUCO BIENBANSUCO
        //{
        //    get;
        //    set;
        //}

        //public virtual PHIEUCHI PHIEUCHI
        //{
        //    get;
        //    set;
        //}

        //public virtual PHIEUTHU PHIEUTHU
        //{
        //    get;
        //    set;
        //}

    }

}