//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class NHANVIEN : HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Required]
        public string MaNV
        {
            get;
            set;
        }

        [Required]
        public string TenNV
        {
            get;
            set;
        }

        [Required]
        public int SoDT
        {
            get;
            set;
        }

        public string DiaChi
        {
            get;
            set;
        }

        [Required]
        public string CMND
        {
            get;
            set;
        }

        [Required]
        public string MaBP
        {
            get;
            set;
        }

        //kết bảng
        //public virtual BOPHAN fBOPHAN
        //{
        //	get;
        //	set;
        //}

        //public virtual PHIEUTHU PHIEUTHU
        //{
        //	get;
        //	set;
        //}

        //public virtual BOPHAN BOPHAN
        //{
        //	get;
        //	set;
        //}

        //public virtual BIENBANSUCO BIENBANSUCO
        //{
        //	get;
        //	set;
        //}

        //public virtual HOADONNHAPHANG HOADONNHAPHANG
        //{
        //	get;
        //	set;
        //}

        //public virtual BOPHAN getBoPhan()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual List<BIENBANSUCO> getListBienBanSuCo()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual List<HOADONNHAPHANG> getListHoaDonNhapHangi()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual List<PHIEUTHU> getListPhieuThu()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

