//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class NHAPHANG
    {
        public int Id
        {
            get;
            set;
        }

        public string SoHD
        {
            get;
            set;
        }

        public string MaNL
        {
            get;
            set;
        }

        public string SoLuong
        {
            get;
            set;
        }

        public string DonGia
        {
            get;
            set;
        }

        public string MaNCC
        {
            get;
            set;
        }
    }

}