//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class PHANHOI: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Nội dung")]
        [Required(ErrorMessage = "Vui lòng nhập nội dung")]
        [DataType(DataType.MultilineText)]
        public string NoiDung
        {
            get;
            set;
        }

        [Display(Name = "Họ tên")]
        [MaxLength(50, ErrorMessage = "Họ tên không quá 50 kí tự")]
        public string TenNguoiPH
        {
            get;
            set;
        }

    }

}

