//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class PHIEUTHU
    {
        public int Id
        {
            get;
            set;
        }

        public string MaPT
        {
            get;
            set;
        }

        public string MaLuot
        {
            get;
            set;
        }

        public string TienHang
        {
            get;
            set;
        }

        public string PhiDichVuKhac
        {
            get;
            set;
        }

        public string KhuyenMai
        {
            get;
            set;
        }

        public string VAT
        {
            get;
            set;
        }

        public string TongTien
        {
            get;
            set;
        }

        public string NgayLap
        {
            get;
            set;
        }

        public string MaNV
        {
            get;
            set;
        }

        public virtual SOTHUCHI SOTHUCHI
        {
            get;
            set;
        }

    }

}