//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class PHIEUTHU : THUCHI
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public override int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã phiếu thu")]
        [Required(ErrorMessage = "Vui lòng nhập mã phiếu thu")]
        [MaxLength(12, ErrorMessage = "Mã phiếu thu không được quá 12 kí tự")]
        public string MaPT
        {
            get;
            set;
        }

        [Display(Name = "Mã lượt khách")]
        [Required(ErrorMessage = "Vui lòng chọn mã lượt khách")]
        public string MaLuot
        {
            get;
            set;
        }

        //kết bảng
        //public LUOTKHACH fLUOTKHACH
        //{
        //	get;
        //	set;
        //}

        //kết bảng
        //public List<YEUCAUMONAN> fYEUCAUMONAN
        //{
        //    get;
        //    set;
        //}
        [Display(Name = "Tiền hàng")]
        [Required]
        [DataType(DataType.Currency)]
        public string TienHang
        {
            get;
            set;
        }

        [Display(Name = "Phí dịch vụ khác")]
        [DataType(DataType.Currency)]
        public string PhiDichVuKhac
        {
            get;
            set;
        }

        [Display(Name = "Khuyến mãi (%)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P2}")]
        public string KhuyenMai
        {
            get;
            set;
        }

        [Display(Name = "VAT (%)")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P2}")]
        public string VAT
        {
            get;
            set;
        }

        // public string TongTien
        // {
            // get;
            // set;
        // }

        //public override string NgayLap
        //{
        //	get;
        //	set;
        //}
        //public virtual LUOTKHACH getLuotKhach()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual NHANVIEN getNhanVien()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

