//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace QuanLyNhaHang.Models
{
    public class PHIEUCHI
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        public string MaPC
        {
            get;
            set;
        }

        public string MaNCC
        {
            get;
            set;
        }

        public string SoTienChi
        {
            get;
            set;
        }

        public string SoHD
        {
            get;
            set;
        }

        public string NgayLap
        {
            get;
            set;
        }

        public string MaNV
        {
            get;
            set;
        }

        //public virtual SOTHUCHI SOTHUCHI
        //{
        //    get;
        //    set;
        //}

    }

}