//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class SOTHUCHI
    {
        public int Id
        {
            get;
            set;
        }

        public string Ngay
        {
            get;
            set;
        }

        public string MaPT
        {
            get;
            set;
        }

        public string MaPC
        {
            get;
            set;
        }

    }

}