//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class THIETHAI: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã biên bản")]
        [Required(ErrorMessage = "Vui lòng nhập mã biên bản")]
        public string MaBienBan
        {
            get;
            set;
        }

        //kết bảng
        //public virtual BIENBANSUCO fBIENBANSUCO
        //{
        //	get;
        //	set;
        //}
        [Display(Name = "Tên đồ hư hại")]
        public string Ten
        {
            get;
            set;
        }

        [Display(Name = "Số lượng")]
        public int SoLuong
        {
            get;
            set;
        }

        [Display(Name = "Đơn vị tính")]
        public string DVT
        {
            get;
            set;
        }

        [Display(Name = "Đơn giá")]
        [DataType(DataType.Currency)]
        public string DonGia
        {
            get;
            set;
        }

        [Display(Name = "Thành tiền")]
        [DataType(DataType.Currency)]
        [Required]
        public string ThanhTien
        {
            get;
            set;
        }



        //public virtual BIENBANSUCO getBienBanSuCo()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

