//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class THIETHAI: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã biên bản")]
        [Required(ErrorMessage = "Vui lòng nhập mã biên bản")]
        [StringLength(12, ErrorMessage = "Mã biên bản không quá 12 kí tự")]
        public string MaBienBan
        {
            get;
            set;
        }
		
		//kết bảng
		public virtual BIENBANSUCO fBIENBANSUCO
		{
			get;
			set;
		}

        [Display(Name = "Tên thiệt hại")]
        public string Ten
        {
            get;
            set;
        }

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng không hợp lệ")]
        public int SoLuong
        {
            get;
            set;
        }

        [Display(Name = "Đơn vị tính")]
        [Required(ErrorMessage = "Vui lòng nhập đơn vị tính")]
        [MaxLength(20, ErrorMessage = "Đơn vị tính không được quá 20 kí tự")]
        public string DVT
        {
            get;
            set;
        }

        [Display(Name = "Đơn giá")]
        public string DonGia
        {
            get;
            set;
        }

        [Display(Name = "Thành tiền")]
        public string ThanhTien
        {
            get;
            set;
        }



        //public virtual BIENBANSUCO getBienBanSuCo()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

