//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class THIETHAI
    {
        public int Id
        {
            get;
            set;
        }

        public string MaBienBan
        {
            get;
            set;
        }

        public string Ten
        {
            get;
            set;
        }

        public int SoLuong
        {
            get;
            set;
        }

        public string DVT
        {
            get;
            set;
        }

        public string DonGia
        {
            get;
            set;
        }

        public string ThanhTien
        {
            get;
            set;
        }

    }

}