//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace QuanLyNhaHang.Models
{
    public class YEUCAUMONAN
    {
        public int Id
        {
            get;
            set;
        }

        public int MaLuot
        {
            get;
            set;
        }

        public string MaMon
        {
            get;
            set;
        }

        public int SoLuong
        {
            get;
            set;
        }

    }
}
