//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class YEUCAUMONAN: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã lượt khách")]
        [Required(ErrorMessage = "Vui lòng nhập mã lượt khách")]
        [MaxLength(12, ErrorMessage = "Mã lượt khách không quá 12 kí tự")]
        public string MaLuot
        {
            get;
            set;
        }
		
		//kết bảng
		public virtual LUOTKHACH fLUOTKHACH
		{
			get;
			set;
		}

        [Display(Name = "Mã món ăn")]
        [Required(ErrorMessage = "Vui lòng nhập mã món ăn")]
        [MaxLength(12, ErrorMessage = "Mã món ăn không quá 12 kí tự")]
        public string MaMon
        {
            get;
            set;
        }
		
		//kết bảng
		public virtual MONAN fMONAN
		{
			get;
			set;
		}

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(0, int.MaxValue, ErrorMessage = "Số lượng không hợp lệ")]
        public int SoLuong
        {
            get;
            set;
        }



        //public virtual LUOTKHACH getLuotKhach()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual MONAN geMonAn()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

