//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class YEUCAUMONAN
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id
    {
        get;
        set;
    }
    public int MaLuot
	{
		get;
		set;
	}

	public int MaMon
	{
		get;
		set;
	}

	public int SoLuong
	{
		get;
		set;
	}



	//public virtual LUOTKHACH getLuotKhach()
	//{
	//	throw new System.NotImplementedException();
	//}

	//public virtual MONAN geMonAn()
	//{
	//	throw new System.NotImplementedException();
	//}

}

