//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyNhaHang.Models
{
    public class YEUCAUNHAPHANG: HETHONG
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id
        {
            get;
            set;
        }

        [Display(Name = "Mã yêu cầu")]
        [Required(ErrorMessage = "Vui lòng nhập mã yêu cầu")]
        [MaxLength(12, ErrorMessage = "Mã yêu cầu không được quá 12 kí tự")]
        public string MaYeuCau
        {
            get;
            set;
        }

        [Display(Name = "Mã nguyên liệu")]
        [Required(ErrorMessage = "Vui lòng chọn mã nguyên liệu")]
        public string MaNL
        {
            get;
            set;
        }

        //kết bảng
        //public virtual NGUYENLIEU fNGUYENLIEU
        //{
        //	get;
        //	set;
        //}

        [Display(Name = "Số lượng")]
        [Required(ErrorMessage = "Vui lòng nhập số lượng")]
        public float SoLuong
        {
            get;
            set;
        }

        [Display(Name = "Mã nhà cung cấp")]
        [Required(ErrorMessage = "Vui lòng chọn mã nhà cung cấp")]
        public string MaNCC
        {
            get;
            set;
        }

		//kết bảng
		//public virtual NHACUNGCAP fNHACUNGCAP
		//{
		//	get;
		//	set;
		//}

        //public virtual HOADONNHAPHANG getHoaDonNhapHang()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual NHACUNGCAP getNhaCungCap()
        //{
        //	throw new System.NotImplementedException();
        //}

        //public virtual NGUYENLIEU getNguyenLieu()
        //{
        //	throw new System.NotImplementedException();
        //}

    }

}

